services:
  # 1. The "Seed" / Lab Environment
  victim:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable_victim
    # THE FIX: Run services, then hang forever so the container doesn't die
    command: sh -c "/bin/services.sh && tail -f /dev/null"
    networks:
      - pentest_net

  # 2. The Agent Backend (FastAPI + Nmap)
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    container_name: agent_backend
    env_file:             
      - .env
    networks:
      - pentest_net
    depends_on:
      victim:
        condition: service_started
      db:
        condition: service_healthy
      chroma:
        condition: service_started # <--- CHANGE THIS FROM service_healthy
    command: >
      sh -c "python scripts/seed_postgres.py && 
             python scripts/seed_chroma.py && 
             uvicorn port_report.api.main:app --host 0.0.0.0 --port 8000"

  # 3. The UI (Streamlit)
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: agent_frontend
    ports:
      - "8501:8501" # Streamlit's default port
    networks:
      - pentest_net
    depends_on:
      - backend

  
  chroma:
    image: chromadb/chroma:latest
    container_name: agent_chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - pentest_net

  db:
    image: postgres:15-alpine
    container_name: agent_db
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpassword
      POSTGRES_DB: agent_brain
    ports:
      - "5432:5432"
    networks:
      - pentest_net
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent -d agent_brain"]
      interval: 5s
      timeout: 5s
      retries: 5  
    
# The invisible router that connects them all safely
networks:
  pentest_net:
    driver: bridge


#docker-compose up --build -d